version: "3"

services:
  jupyterlab:
    build: .

    ports:
      - 8888:8888
    volumes:
      - ./datadir:/work

    command: --NotebookApp.password="${JUPYTERLAB_PASSWORD}"

    restart: always

    env_file: .env
    environment:
      PASSWORD:
